services:
  web:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
    command: npm run dev
    restart: always
