services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
    working_dir: /app
    command: npm run dev
    restart: always
